### ISSUE TITLE
Import "flask" could not be resolved

### ISSUE THREAD

**Issue by Einsteinia11** [app-generator/flask-atlantis-dark#11]
Hey 🖐,
I followed all the steps but I am getting the below errors while I am trying to run the last step
`$ flask run`
<img width="719" alt="error" src="https://user-images.githubusercontent.com/97274353/232572262-68eb1292-9440-4e4b-baa4-5184794a80b1.PNG">
General information: I am working on VS Code editor

**Comment by Einsteinia11** [comment]
Hello🙏,
I have executed the set up through README itself!

Here's the whole screenshot of my entire set up in VsCode 👇

<img width="960" alt="error" src="https://user-images.githubusercontent.com/97274353/232824840-501af59d-4ff0-47e4-9b96-6a388e2fe63f.PNG">

Whatever is written in the tip as you can see in the image I have already done that and also Flask is also installed but still don't know why this type of error occurring🤔!

Thank You🙇‍♀️!

**Comment by app-generator** [comment]
The `FLASK_APP` is not exported. 
Seems that you're using `PowerShell` and the missing command is this one: 

`$env:FLASK_ENV = "development"` 

Please retry and let us know your progress.

**Comment by Einsteinia11** [comment]
Now this error!
<img width="960" alt="error" src="https://user-images.githubusercontent.com/97274353/232864924-97f98c86-7b51-4f97-b556-930bce82b577.PNG">

**Comment by app-generator** [comment]
`pip3 install -r requirements.txt`

**Comment by app-generator** [comment]
P.S. all steps are listed on the README. 

Any Flask APP needs the following:

- install modules via `PIP` directly in the system or using a `Virtual ENV`
- Export the `FLASK_APP` variable to inform Flask about the entry point
- Run `flask run`
  - this will start the app on port `5000`
//OR
- Run `flask run --port=5077` using a different PORT
  - in this case, the APP starts on port `5077`

Let us know your progress.

**Comment by Einsteinia11** [comment]
Done!🚀

This helped me👇
Install modules via PIP directly in the system or using a Virtual ENV
`pip install -r requirements.txt`

Actually I was executing the above command in cmd and didn't did in powershell :')
Thank you so much!
Have a great day🙇‍♀️!

**Comment by app-generator** [comment]
Glad it worked. 
Let us know anytime if you need further assistance. 
🚀🚀
