### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by Jimmykimpo** [app-generator/flask-atlantis-dark#4]
I cloned this project and followed your YouTube video step by step however when I run it I get an Internal Server Error 500 on the browser. I followed all Windows commands required for setup.

**Comment by app-generator** [comment]
Hello @Jimmykimpo, 

Please specify the commands and python version. 

Before running the commands listed in the [README](https://github.com/app-generator/flask-dashboard-atlantis-dark#how-to-use-it) please double-check  the Python version:

```bash
python --version
```

On a Windows testbed this command shows `Python 3.8.4`
Let us know your progress.

**Comment by Jimmykimpo** [comment]
I am on python 3.9.1. As for the commands, I copied and pasted the commands you have listed (making sure I chose the Windows options for the ones that apply).

**Comment by app-generator** [comment]
Hello,

We've re-test the kit (fresh install) on Windows and Linux (Ubuntu
18.04LTS). The codebase is ok.
Try to start the app in DEBUG mode:
Let us know your progress.

$ # Set up the DEBUG environment
$ # (Unix/Mac) export FLASK_ENV=development
$ # (Windows) set FLASK_ENV=development
$ # (Powershell) $env:FLASK_ENV = "development"

**Comment by marvinschmidtke** [comment]
Hi guys,

im getting the same ERROR with the following stacktrace:

![image](https://user-images.githubusercontent.com/19649604/116784248-826c9280-aa93-11eb-8d94-6f9ab407a47a.png)

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
