### ISSUE TITLE
uh im get 500 error code can u help me out?

### ISSUE THREAD

**Issue by Afnanksalal** [app-generator/flask-atlantis-dark#5]
uh im get 500 error code can u help me out?

**Comment by app-generator** [comment]
Hello @afnan007a,

Thank you for using our products. For sure we can help. 
Please reply with the following information: 

- OS Type and Version (Windows, Ubuntu .. etc)
- Python Version - to check this type `python --version` in the terminal
- The steps you're following
- The `error text` as displayed in the terminal
- The `URL` that generate the error (login, register) or a particular page
- If relevant, a screen-shot 

Once we have the information, we'll get back to you with some guidance. 

**AppSeed Support**

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
